### ISSUE TITLE
Input / button

### ISSUE THREAD

**Issue by Phil-b-l** [sammachin/node-red-contrib-ngrok#13]
Just installed the node and it has no input connection nor button so I cant send a msg to tell it what to do. I have this on other node red installs and no problem but they are older. I see you have done some updates but now it doesn't seem to work. It also doesnt seem to create the .yml file in ngrok2 which also doesn't exist. I expect it's me being a muppet as I am finding my way round this but if you could point me in the right direction that would be great. 
Many Thanks

**Comment by nymJ** [comment]
Same problem here.

**Comment by zeldalegends** [comment]
Double click ngrok node to enter "Edit ngrok node", and select "Button" or "Input port" in "Input Type" setting.

**Comment by zeldalegends** [comment]
> Just installed the node and it has no input connection nor button so I cant send a msg to tell it what to do. I have this on other node red installs and no problem but they are older. I see you have done some updates but now it doesn't seem to work. It also doesnt seem to create the .yml file in ngrok2 which also doesn't exist. I expect it's me being a muppet as I am finding my way round this but if you could point me in the right direction that would be great.
> Many Thanks



> Same problem here.

Double click ngrok node to enter "Edit ngrok node", and select "Button" or "Input port" in "Input Type" setting.

**Comment by sammachin** [comment]
There is a slight glitch where if a node is newly placed on the canvas it doesn't have an input or a button, but as soon as you open the properties and click done (even without changing anyting) it will get its default of an input port.
I don't think this is a HUGE issue as generally you would need to configure something in the node before you can use it anyway.

Regarding the yml file this node doesn't interact with ngrok installed on the system at all it uses its own config for the authtoken in the node.
