### ISSUE TITLE
Improvement suggestions

### ISSUE THREAD

**Issue by Steve-Mcl** [sammachin/node-red-contrib-ngrok#14]
Hi, I wonder if you are still interested in suggestions?

### Add name to auth token 
As you provide no name for config node, they all appear as "authtoken"
![image](https://user-images.githubusercontent.com/44235289/103308281-f590ca00-4a09-11eb-89c4-67e2acc500dd.png)

### Allow settings to be set via input message or flow/global...
* Port 
* Region 
* Protocol 
* Subdomain 
* Auth

Ideally, you would make these fields [TypedInput](https://nodered.org/docs/api/ui/typedInput/)s that permit static entry or a `msg` property or a `flow`/`global` property

example...
![dFqp6hio2E](https://user-images.githubusercontent.com/44235289/103309829-080d0280-4a0e-11eb-8023-d5fd4a029927.gif)

<details>
 <summary>Code example to make typed inputs</summary>
<pre><code>
         //NOTE: Code is not 100% complete (the selected `type` needs to be stored)
                $("#node-input-region").typedInput({
                    default:"region",
                    types: [                    
                        {
                            value:"region",
                            label:"Region", 
                            title: "Region", 
                            icon:"fa fa-globe",
                            showLabel:false,
                            multiple:false,
                            options:[
                                { label: "US",  value: "us" },
                                { label: "Europe",  value: "eu" },
                                { label: "Asia/Pacific",  value: "ap" },
                                { label: "Australia",  value: "au" },
                                { label: "South America",  value: "sa" },
                                { label: "Japan",  value: "jp" },
                                { label: "India",  value: "in" },
                            ],
                            default: "us"
                        },
                        ,'msg', 'flow', 'global', 'str', 'env'
                    ]
                })
                $("#node-input-proto").typedInput({
                    default:"protocol",
                    types: [
                        {
                            value:"protocol",
                            label:"Protocol", 
                            title: "Protocol", 
                            icon:"fa fa-code",
                            showLabel:false,
                            showIcon:true,
                            multiple:false,
                            options:[
                                { label: "HTTP",  value: "http" },
                                { label: "TCP",  value: "tcp" },
                            ],
                            default: "HTTP"
                        },
                        ,'msg', 'flow', 'global', 'str', 'env'
                    ]
                })
                $("#node-input-port").typedInput({
                    default:"num",
                    types: [ 'msg', 'flow', 'global', 'num', 'env'
                    ]
                })
                $("#node-input-subdomain").typedInput({
                    default:"str",
                    types: [ 'msg', 'flow', 'global', 'str', 'env'
                    ]
                })
                $("#node-input-auth").typedInput({
                    default:"str",
                    types: [ 'msg', 'flow', 'global', 'str', 'env'
                    ]
                })
</code></pre>
</details>

**Comment by sammachin** [comment]
Hi,

Sorry I missed this message before, those look like good improvements, would you like to submit a PR?

Sam

**Comment by sammachin** [comment]
I've implemented the authtoken name lable in 1.2.1 but the other bits need some more work.

**Comment by Steve-Mcl** [comment]
Hi @sammachin sorry I missed your comment. I would have done a PR (sorry). 

Do you need help?

**Comment by sammachin** [comment]
No worries, I'm comfortable enough doing the changes its more just a question of time and priorities, I'm not totally convinced that typed inputs on each of those fields adds that much benefit, I imagine that 99% of people will just use static settings, curious what the use case is here?
Having said that I'd gladly include them if someone sent a PR as I don't think it adds complexity & confusion for users so long as the defaults are what they currently are.

**Comment by Steve-Mcl** [comment]
You are right, most people will use defaults/static values but there are those who will want to programmatically set the values. When they can't, they'll drop your node and make a rival node or use an exec node with command line parameters. 

Use case: a lot of machine builders will build a flow with msg or context values as the parameters so that they can reuse their flows in a dynamic way & simply provide a UI for setting up the parameters by the user. If the inputs are not programmable, they cannot use your node. 

Other use cases include: when you want several ngrok connection types & the ability to switch between them via some msg property or other logic condition, you can achieve that with one node on the flow instead of several (since the values are not static) 

I would definitely agree to the defaults being set to the original values for backwards compatibility.

**Comment by Steve-Mcl** [comment]
Hi @sammachin I have updated my fork of your node with dynamic options here: https://github.com/Steve-Mcl/node-red-contrib-ngrok/tree/dynamic-options 

This is a quick demo...
![VvMKxbBZVQ](https://user-images.githubusercontent.com/44235289/120344843-dddbab80-c2f1-11eb-9259-9c0bb1bcbf41.gif)


If you are interested, I will do a PR - or add me as a collaborator?

**Comment by sammachin** [comment]
Hi @Steve-Mcl  

That looks good, yes please send a PR and I'll merge it and make a new release, there's a couple of minor points I'd change if you want to do before the PR otherwise I can do it before the release:

The Host header, the example shows  the port number and while this is technically correct it only needs to be set if its not the defualt and in the way ngrok would be used (forwarding to a server with multiple vhosts its very unlikely to then be routing on port number as well) so perhaps just remove the `:port` from the placeholder text. I feel this would be less confusing to users and those that know to set it would figure it out from the ngrok & specs.

The other thing is the port field, ngrok supports forwarding to something other than localhost, you can specify a hostname or ip and port eg `192.168.1.1:80`. So we could either:
Make the field a string instead of a number or add another field for host and have that default to 127.0.0.1 then contstruct the string in the js file?

**Comment by Steve-Mcl** [comment]
No problem, makes sense. I'll fix up those couple of items then do the PR

**Comment by Steve-Mcl** [comment]
Hi @sammachin 

I have finished the mods and (because I cannot resist) tweaked a few more things to (hopefully) improve the UI...

![image](https://user-images.githubusercontent.com/44235289/120774224-fcbc8680-c519-11eb-9af0-a43d08a98d63.png)

* Built in help much more complete now
* Prevent error when no Authtoken/config is selected
* Show input port when added to editor (previously the input port would be missing until config was OKed)
* Re-ordered UI elements to put Name at the bottom (node-red design direction)
* Renamed "input type" to "trigger" (more descriptive?)

Also, added a dynamic control demo...
![chrome_TnespuIKxs](https://user-images.githubusercontent.com/44235289/120780932-7bb4bd80-c520-11eb-98e4-7278521395de.png)


Hope you are ok with these tweaks?


Feel free to accept / revert whatever suits.

PR to follow shortly.

**Comment by sammachin** [comment]
That all looks brilliant! I need to take a look at how you stopped the
erroring on missing authtoken as thats been bugging me!

In terms of forwarding ngrok to another host on the network have you just
gone with the port field as a string and entering `192.168.1.1:80` kinda
setup?

One really minor thing but in the help text I'm not sure about STRONGLY
recommending auth, the readme has a warning to secure your editor which is
the better option IMO, and the most common use of ngrok is to receive
external webhooks so adding auth to those endpoints could well cause
confusion as its not clear on most API platforms if/how to set that up.

Other that that yes please send the PR through, any thoughts on if this
should be a 2.0 or 1.4 release? I don't think there's any breaking changes
as such, but its quite a big step?

Sam

**Comment by Steve-Mcl** [comment]
> I need to take a look at how you stopped the
erroring on missing authtoken as thats been bugging me

add `required: false` to the `default` property 😎 

>One really minor thing but in the help text I'm not sure about STRONGLY
recommending auth, the readme has a warning to secure your editor which is
the better option IMO, and the most common use of ngrok is to receive
external webhooks so adding auth to those endpoints could well cause
confusion as its not clear on most API platforms if/how to set that up.

Please feel free to "fix up" the built in help as you see fit :) 

> In terms of forwarding ngrok to another host on the network have you just
gone with the port field as a string and entering `192.168.1.1:80` kinda
setup?

Yes.  I did consider your earlier suggestion but didnt get around to it. It would be tidier (on the UI) and more intuitive to the user  but a bit fiddly under the hood. I will leave that up to you.


> Other that that yes please send the PR through, any thoughts on if this
should be a 2.0 or 1.4 release? I don't think there's any breaking changes
as such, but its quite a big step?

Either/Or 😄  - perhaps 2.0.0 to signify big changes (and just in case there is a slight change when a user upgrades the node with an existing flow in place (though i did try to keep everything defaulting to original options)

**Comment by sammachin** [comment]
ha ha yes obvious really I didn't even think to try that!

I'll merge your PR now and make a couple of tweaks before a release as 2.0

Thanks for all of this.

**Comment by Steve-Mcl** [comment]
Good stuff.

Sam, i think 2.0.0 is the right choice since I also updated the deps (ngrok now on 4.0.1 - which is a major change)

PS, it works well so far in testing.

**Comment by sammachin** [comment]
2.0.0 released, tweaked a couple of defaults and also added in the host param. Thanks for all your work on this.
