### ISSUE TITLE
Connect error: cant set authtoken

### ISSUE THREAD

**Issue by mastin-zgz** [sammachin/node-red-contrib-ngrok#17]
Hi!

The node red log give me this error and the node dont work.

The token in another node red works well.

Any idea?

Thanks!

**Comment by sammachin** [comment]
I'm not really sure what to suggest, especially if the token works in another instance, are they both the same versions?
Only thing that comes to mind is are you trying to have both instanced connect to ngrok at the same time? There's a limit on the number of connections an account can make although I'm not sure what the error is

**Comment by sammachin** [comment]
Closing due to no response
