### ISSUE TITLE
unable to start tunnel to HTTPS node red

### ISSUE THREAD

**Issue by vibraHome** [sammachin/node-red-contrib-ngrok#25]
Can´t connect to node red via ngrok when node red listens on https.
When I open the tunnel I only get 502 Bad Gateway.
After changing to http it works.
node-red-contrib-ngrok 1.1.1 works but Version 2.0.0 not.

Thank you

**Comment by sammachin** [comment]
Hi @vibraHome 

You wouldn't normally use ngrok to connect to an HTTPS host as ngrok can terminate the HTTPS requests itself and then forward via a secure tunnel to localhost and make the request over plain http there.

Ngrok as a service does offer TLS tunnels however that option is not exposed in the node-red package at the moment, I'm not sure how this was working for you in 1.1.1 can you share the config that you had it that node?

**Comment by vibraHome** [comment]
Hi @sammachine,

here ist my config. This one works in version 1.1.1

[
    {
        "id": "b303f521.3985b8",
        "type": "ngrok",
        "z": "986325a5.c019c",
        "port": "https://192.168.0.17:1880",
        "creds": "f7f3bd2a.238608",
        "region": "eu",
        "proto": "http",
        "subdomain": "",
        "name": "node red",
        "auth": "",
        "inputtype": "port",
        "inputs": 1,
        "x": 1520,
        "y": 1960,
        "wires": [
            [
                "22054a7d.0f3bc6"
            ]
        ]
    },
    {
        "id": "f7f3bd2a.238608",
        "type": "ngrokauth"
    }
]

after upgrade to version 2.0.0 it stops working.

**Comment by sammachin** [comment]
OK, so in 2.0.0 we've split the host section out of the port field, the port should only contain the TCP port that you want to connect to then if you're connecting to a host different to where ngrok is running put that IP address into the host field (don't use the `https://` prefix)

It's a bit of strange config you have using ngrok to connect to an https host, typically you would have the host on plain http and have ngrok take care of the SSL, or use TLS with ngrok and have it just forward the certificate right through, but your setup does seem to work (I'm just not totally sure its supported within ngrok itself!)

Try this config in the node https://cdn.zappy.app/50afd6919ea15e91d295b70f5c316e7f.png

I've set the binding to HTTPS only which means that ngrok will only accept https connections to the xxx.ngrok.io address not plain HTTP ones which i assume you want, you could change this back to HTTP &* HTTPS if you wanted external connections to be able to use plain http.

Sam
