### ISSUE TITLE
Custom subdomain domain

### ISSUE THREAD

**Issue by ThWunderlin** [sammachin/node-red-contrib-ngrok#26]
Hello is it possible to include own domain?
For me only the subdomain.ngrok.io work, no sudomain.test.com for example.

Thanks

**Comment by sammachin** [comment]
Hi @ThWunderlin sorry for the delay I missed you comment.

Have you configured your custom domain in ngrok? https://ngrok.com/docs/cloud-edge#domains

TBH I've not tested this feature, I hadn't even noticed ngrok offered it but I'll give it a go

**Comment by ThWunderlin** [comment]
Hello @sammachin no problem
I tested the domain on Windows with Ngrok this worked but in NodeRed it did not work.
As I understood it, I would have to set the domain also in NodeRed otherwise it does not work.

Thanks

**Comment by sammachin** [comment]
It looks like ngrok uses different parameters.
`-subdomain=sammachin` will give you a tunnel at sammachin.ngrok.io
but its `-hostname=tunnel.sammachin.com` if you want to use your own domain instead. 

Thats a bit annoying, it should be possible to add the config option to the Node-RED package I just need to think about the best UX option so we don't have 2 confusing boxes

**Comment by ThWunderlin** [comment]
Yes that would be great. I can then test it for you :-)
Or can I help you otherwise?

**Comment by sammachin** [comment]
Not sure if you're still using this but I've just updated the node to use the newer ngrok client and I've added in support for full domains, the subdomain field is now just domain and you can enter a single subdomain string or a FQDN for a hostname. Give 2.1.0 a try
