### ISSUE TITLE
TCP connection

### ISSUE THREAD

**Issue by JCsound** [sammachin/node-red-contrib-ngrok#28]
When I try to use it with TCP it gives an error and does not start ngrok.

**Comment by sammachin** [comment]
HI @JCsound Sorry I missed the notification for this, can you provide some more details and share your config? I've just tested here and it works for me

**Comment by sammachin** [comment]
Also do you have a paid ngrok account? the TCP tunnels are not supported on the free plan

**Comment by JCsound** [comment]
Hi, I'm going to do another test. But my account is free and TCP still works if I put the command manually.
