### ISSUE TITLE
Update ngrok package to 5.0.0

### ISSUE THREAD

**Issue by jchcc** [sammachin/node-red-contrib-ngrok#30]
All ngrok agents version 3.1 and older will stop working on January 15th, 2024 for all free users.

**Comment by sammachin** [comment]
yes I got the email this morning too, I'll look at doing the update over the christmas break, first glance it look like a little more than just updating the package.json as some of the APIs have also changed

**Comment by grawsom** [comment]
@sammachin And if you need help in testing - I will gladly help where I can

**Comment by twocolors** [comment]
@sammachin mb use https://ngrok.github.io/ngrok-javascript/ ?

**Comment by sammachin** [comment]
I've just published 2.1.0 of the package, this uses the 5.0.0-beta.2 release of node ngrok, the areas that have been changed are the binding and the auth so if you use those features especially please test and report back.

I'm not totally sure how this will handle upgrading existing clients with config files in place if you have any issues please raise an issue and mention your OS and if you have ngrok installed directly as well as part of the package, I think you _may_ need to remove the ngrok config file if its there from an older version.

It also looks like ngrok have stopped allowing unregistered access so you will need to register and set an auth token if you didn't previously, there's a free tier though.

Ideally I would like to replace this with the official ngrok pacakge as mentioned by @twocolors but thats a lot more work and basically means rewriting the node, I'll consider a 3.0.0 release using that package especially if node ngrok gets deprecated, however I'm not really using ngrok much day to day now in my work and ngrok wern't very forthcoming on giving me a discount on my renewal last year for maintaining this package so its not top of my priorities.

**Comment by twocolors** [comment]
hi thanks for the update

@sammachin If you don’t want to support this module anymore or don’t have time, pass it to me (maintenance npm).

For example, I'm interested in supporting native integration

**Comment by WombatHollow** [comment]
Thanks for quick update, but I am afraid it is only part functional.   To summarise
You will to (on a Raspi)

1.  `nano /home/pi/.ngrok2/ngrok.yml`
2.  add a line `version : 1`
3.  exit and save the file (no filename change)
4.  should run, no need to restart NR

**More Detail**
I just installed the update to my existing NGROK nodes, the node didn't  report any issues with the old data, but sending a msg.payload = "on" produced Nothing and leaves the node on idle state. Sending a msg.payload = "off" produced the expected response and leaves the node on disconnected state.  A subsequent "on" was no different than the first.
 I opened and forced changes in both NGROK nodes and redeployed but no change.

But in the Log I see 
`Connect error:
ERROR:  Error reading configuration file '/home/pi/.ngrok2/ngrok.yml': `version` property is required.
ERROR:
ERROR:  If you're upgrading from an older version of ngrok, you can run:
ERROR:
ERROR:      ngrok config upgrade
ERROR:
ERROR:  to upgrade to the new format and add the version number.
`
ngrok doesn't run but the above .yml file exists and only contains the authtoken

I edited it with nano and added a line `version : 1`

that fixes it.

**My system**
NR 3.1.0
NPM 18
Raspi 3B running latest Raspian as of a few months ago

**Comment by sammachin** [comment]
@WombatHollow thanks for the report, yeah I thought there might be something like that, 2 questions:

Did you have ngrok installed locally on the pi as well as the NR package?

Do you have an authtoken specified in the Node-RED ngrok  config node?

**Comment by WombatHollow** [comment]
No, Ngrok is not locally installed on my pi as far as I can determine.   It
doesn't recognise ngrok as a command (with or without sudo).   In the pi
director there are two relevant sub directories, .ngrok1 that has 2
compressed files, and .ngrok2 that has at least the configuration  file I
edited.

 Both fields in the ngrok configuration node are filled.  Not checked if
the authtoken are the same, but I have only ever had one.

**Comment by grawsom** [comment]
@sammachin  - here is my feedback, so far
I have now tested on 3 different instances, docker (NR), Raspberry Pi 3b+, Windows 11.
I use token on all instances (free)

Docker was 2.0.1 did update to 2.1.0 - NP, stille working as exspected.

RPI - new install - default settings, only added the token - working fine with stting to use localhost (NR) - using with buttom, and then copying url.

Win 11 - was updated to 2.1.0 , and is still working fine. 

My yml on eg. Win11 only have the token inside.
RPI - no yml, but 8MB zip file :-)

System
Synology NAS (Docker), RPI and windows NR 3.1.3

**Comment by WombatHollow** [comment]
Ok.  On Rpi the .yml file was in pi/.ngrok2 directory, the big zip file (2
of) were in .ngrok1 directory.   Maybe mine is different as I update the
node (through pallette) rather than new Install.

At least works in all 3 environments,  some may need the .yml update but
that will be a clear from the error in the NR log (but not on debug pane).

Anyway, thanks again.

**Comment by node-red-italia** [comment]
> Thanks for quick update, but I am afraid it is only part functional. To summarise You will to (on a Raspi)
> 
> 1. `nano /home/pi/.ngrok2/ngrok.yml`
> 2. add a line `version : 1`
> 3. exit and save the file (no filename change)
> 4. should run, no need to restart NR
> 
> **More Detail** I just installed the update to my existing NGROK nodes, the node didn't report any issues with the old data, but sending a msg.payload = "on" produced Nothing and leaves the node on idle state. Sending a msg.payload = "off" produced the expected response and leaves the node on disconnected state. A subsequent "on" was no different than the first. I opened and forced changes in both NGROK nodes and redeployed but no change.
> 
> But in the Log I see `Connect error: ERROR: Error reading configuration file '/home/pi/.ngrok2/ngrok.yml': `version`property is required. ERROR: ERROR: If you're upgrading from an older version of ngrok, you can run: ERROR: ERROR: ngrok config upgrade ERROR: ERROR: to upgrade to the new format and add the version number.` ngrok doesn't run but the above .yml file exists and only contains the authtoken
> 
> I edited it with nano and added a line `version : 1`
> 
> that fixes it.
> 
> **My system** NR 3.1.0 NPM 18 Raspi 3B running latest Raspian as of a few months ago

hi, I'm in the same situation, I have install only the node by node-red palette. I have try your suggestion.

NR3.1.3
NPM18
OS Ubuntu 20.04LTS

**Comment by WombatHollow** [comment]
> > Thanks for quick update, but I am afraid it is only part functional. To summarise You will to (on a Raspi)
> > 
> > 1. `nano /home/pi/.ngrok2/ngrok.yml`
> > 2. add a line `version : 1`
> > 3. exit and save the file (no filename change)
> > 4. should run, no need to restart NR
> > 
> > **More Detail** I just installed the update to my existing NGROK nodes, the node didn't report any issues with the old data, but sending a msg.payload = "on" produced Nothing and leaves the node on idle state. Sending a msg.payload = "off" produced the expected response and leaves the node on disconnected state. A subsequent "on" was no different than the first. I opened and forced changes in both NGROK nodes and redeployed but no change.
> > But in the Log I see `Connect error: ERROR: Error reading configuration file '/home/pi/.ngrok2/ngrok.yml': `version`property is required. ERROR: ERROR: If you're upgrading from an older version of ngrok, you can run: ERROR: ERROR: ngrok config upgrade ERROR: ERROR: to upgrade to the new format and add the version number.` ngrok doesn't run but the above .yml file exists and only contains the authtoken
> > I edited it with nano and added a line `version : 1`
> > that fixes it.
> > **My system** NR 3.1.0 NPM 18 Raspi 3B running latest Raspian as of a few months ago
> 
> hi, I'm in the same situation, I have install only the node by node-red palette. I have try your suggestion.
> 
> NR3.1.3 NPM18 OS Ubuntu 20.04LTS

And did that fix it or you still have problem?

**Comment by node-red-italia** [comment]
No, the ON or True command has no effect, the "off" or "False" command correctly disconnects. I don't know how to recover the log you mentioned.

Thanks

**Comment by WombatHollow** [comment]
If you go into the pi command line and type node-red-log, you can then see
you logs.

Or

At command line stop and start node red with
node-red-stop
node-red-start

Then it will start and display logs (don't ctrl-c to get back to command
line), once started go back to NR Web interface and initiate a on command,
check log for response.

**Comment by node-red-italia** [comment]
Yes, on node-red log I haven't messagge for ngrok.

**Comment by sammachin** [comment]
versions 3.0.2 has now been published and uses the new ngrok-javascript client, 
Going forward none of the older versions will be supported so please update to 3.x
