### ISSUE TITLE
 Pay-as-you-go Monthly

### ISSUE THREAD

**Issue by vibraHome** [sammachin/node-red-contrib-ngrok#33]
After to much usage in my free account i thought i switch to the  Pay-as-you-go Monthly subscription.
I am now not able to connect to this account via node red.
If i send "on" to the node, nothing happens. After sending "off" the node tells my "disconnected".
If i start ngrok manual, it tells me, i have to use the --domain flag.
Using this flag the connection will establish.

What can i do, to connect to my account.

Greetings
Thomas

**Comment by sammachin** [comment]
@vibraHome can you share a screenshot of your node configuration.

Is the authtoken configured in the node the same one as listed on your ngrok account?

Which version of the node are you using

**Comment by vibraHome** [comment]
![2024-01-30 10_51_41-Node-RED _ f46a-2a02-8070-6481-4c20-dea6-32ff-fe81-35ce ngrok-free app und 1 wei](https://github.com/sammachin/node-red-contrib-ngrok/assets/73103324/ec158c47-c7de-4dac-ae3f-626c9dbeab98)

I use Version 1.1.1 but also the current one.
The authtoken is the same as the one in my account.
If I switch the token to a free account it works.
The problem is the --domain flag when using the Pay-as-you-go account

**Comment by sammachin** [comment]
I’d reccomend using the latest version of the node there have been a number of changes/fixes, 
You can enter either a domain or a subdomain in that field in the node so try putting one of your reserved domains in there.

We’ll be releasing a brand new 3.0 very soon using the new official ngrok SDK too.,

**Comment by sammachin** [comment]
versions 3.0.2 has now been published and uses the new ngrok-javascript client,
Going forward none of the older versions will be supported so please update to 3.x
