### ISSUE TITLE
Supported Node and Node-RED versions

### ISSUE THREAD

**Issue by grawsom** [sammachin/node-red-contrib-ngrok#36]
Informations for the module 
Supported Node-RED Version: 3.1.5,2.2.3
Node.js Version: >=16.0.0

Are there any chance for a lower support eg. Node 14 and NR 2.2.2

EDIT: maybe an error - there is no 2.2.3 Node-RED version

**Comment by sammachin** [comment]
Hi,

Thats taken from the scorecard which just checks and reports againt whatever the latest versions of node-red are that are still in maintance, 2.2.3 is the latest maint release of the 2.x line.

The node should work fine with any node-red greater than 2.0.0 which is whats defined in the package.json (it might work on 1.x too but I'm not going back that far to check!)

Unfortunatly Node16 is a requirement of the underlying ngrok package. node 14 is VERY old now.
