### ISSUE TITLE
[REQUEST]Adding username/password

### ISSUE THREAD

**Issue by cymplecy** [sammachin/node-red-contrib-ngrok#6]
Hi 
@biglesp has done a blog on using ngrok and I tried it out - all good :)

https://bigl.es/friday-fun-sms-controlled-neopixels/

But, as you know, it does leave your Node-RED completey exposed if someone happens to find your url (unlikely in practice unless you pay and get a perm ngrok url)

but ...  :)
I had a play running ngrok in terminal and if I launch like this
![image](https://user-images.githubusercontent.com/2357428/68127993-d930f480-ff0e-11e9-8bec-1e27ebe6ed73.png)

I can stick the username/password in the Nexmo settings and voila - we have security (well - as long as we use something different from admin/password of course :)  )
![image](https://user-images.githubusercontent.com/2357428/68127859-9b33d080-ff0e-11e9-9991-be8d0a955321.png)

So, any chance of adding in this as an option in your node?  -Does the underlying ngrok lib support it?

Simon

**Comment by sammachin** [comment]
Hi @cymplecy 
Interesting, I didn't know ngrok had that, it looks as if the underlying library does allow that to be set, however the only drawback here is that then all your webhooks would also have the same authentication in front of them, I'm slightly concerned this would create more problems for people to debug, I'll have a play around with this when I get some free time and see how easy it is to implement,

**Comment by okhiroyuki** [comment]
Hi @cymplecy 
Modifications have been made in [this repository](https://github.com/okhiroyuki/node-red-contrib-ngrok), including authentication options.

Can I make a pull request?
I actually raised a pull request related to an error before but dropped it because there was no response.

**Comment by sammachin** [comment]
Implemented in the 1.0.0 release using a PR from @kingkong123 

Sorrt @okhiroyuki I missed your comment until I'd merged the previous PR, please take a look at the current master and if you can see any improvements submit a PR
